<?php
session_start();
?>

<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Contact Form</title>
  <meta name="description" content="Simple Contact Form">
  <meta name="author" content="CodeRider">
</head>

<body>
<?= (isset($_SESSION['contact-form']['error'])) ? $_SESSION['contact-form']['error']:'' ?>
<?= (isset($_SESSION['contact-form']['success'])) ? $_SESSION['contact-form']['success']:'' ?>
  <form action='/mailer.php' method='post'>
    <label for='name'>Name:</label>
    <p>
      <input name='name' id='name' type='text' value='<?= (isset($_SESSION['contact-form']['inputs']['name'])) ? $_SESSION['contact-form']['inputs']['name']:'' ?>'>
    </p>
    <label for='content'>Message:</label>
    <p>
      <textarea name='content' id='content'><?= (isset($_SESSION['contact-form']['inputs']['content'])) ? $_SESSION['contact-form']['inputs']['content']:'' ?></textarea>
    </p>
    <input type='submit' value='Send'>
  </form>
  
<?php
  if (isset($_SESSION['contact-form'])) {
    unset($_SESSION['contact-form']);
  }
?>
  
</body>
</html>